// EDIT THIS FILE TO ADD, REMOVE, OR REPLACE FEATURED PROJECT MEDIA.
window.projects = {
  jbl:{type:'COMMERCIAL CGI · PRODUCT VISUALIZATION',title:'JBL — CGI Product Advertisement',description:'A cinematic independent spec commercial exploring how a portable speaker can be presented through warm light, lifestyle framing and premium CGI.',role:'Creative direction · 3D/CGI · Lighting · Animation · Editing',tools:'Blender · After Effects · Premiere Pro',projectType:'Independent spec concept — not commissioned by JBL',overview:'Built as a complete product-film exercise from visual concept through final edit. The project focuses on product presence, cinematic lighting, camera movement and a polished advertising rhythm.',video:'assets/videos/jbl.mp4?v=2',poster:'assets/jbl.jpg'},
  dragon:{type:'VFX · 3D & CGI · CINEMATIC EDITING',title:'Dragon Cry — Live-Action Fan Adaptation',description:'A fan-made live-action interpretation inspired by Fairy Tail: Dragon Cry, combining 3D environments, creature shots, destruction effects, compositing and cinematic editing.',role:'3D/VFX · Environment work · Compositing · Editing · Sound design',tools:'Blender · After Effects · Premiere Pro',projectType:'Personal fan project · Independent and unofficial',overview:'An older personal project developed as a portfolio piece to practice large-scale fantasy visuals and live-action-style VFX. The final cut combines dragon imagery, fire, city destruction, character shots and sound design into a short cinematic sequence.',video:'assets/videos/dragon-cry.mp4',poster:'assets/dragon-cry.jpg'},
  gthing:{type:'COMMERCIAL CGI · PRODUCT ANIMATION',title:'GThing Freshness — CGI Beverage Advertisement',description:'A stylized beverage film built around bold product presentation, fresh color and ice/liquid-inspired motion.',role:'3D/CGI · Product animation · Lighting · Editing',tools:'Blender · After Effects · Premiere Pro',projectType:'CGI advertising project',overview:'The visual direction uses high-contrast product framing and energetic freshness cues to make the can feel tactile, cold and immediately readable as an advertising hero object.',video:'assets/videos/gthing.mp4',poster:'assets/gthing.jpg'},
  vinfizz:{type:'COMMERCIAL CGI · PRODUCT ANIMATION',title:'VinFizz Cherry — CGI Beverage Advertisement',description:'A product-focused beverage animation using cherries, liquid motion and bold red art direction.',role:'3D/CGI · Animation · Lighting · Editing',tools:'Blender · After Effects · Premiere Pro',projectType:'Independent CGI advertising project',overview:'Designed as a compact commercial piece with the product always at the center. Floating fruit, fluid forms and a saturated visual palette support a playful cherry-flavored identity.',video:'assets/videos/vinfizz.mp4',poster:'assets/vinfizz.jpg'},
  witch:{type:'3D ENVIRONMENT · LIGHTING · RENDERING',title:'The Witch House',description:'A cinematic stylized environment focused on atmosphere, framing and visual storytelling.',role:'Environment design · 3D scene building · Lighting · Rendering',tools:'Blender · Photoshop',projectType:'Personal 3D environment project',overview:'The scene uses a crooked glowing house, dense forest silhouettes and warm-vs-cool contrast to build a strong story image without relying on character animation.',image:'assets/witch-house.png',gallery:['assets/gallery/witch-house-alt.png']},
  dict:{type:'PROFESSIONAL MOTION GRAPHICS · EVENT VISUALS',title:'DICT — 45th Anniversary Motion Graphics',description:'A full-length motion-graphics production created for a Department of Information and Communications Technology event during professional work.',role:'Motion graphics · Visual development · Animation · Final production',tools:'After Effects · Photoshop · Premiere Pro',projectType:'Professional event production',overview:'One of my first complete long-form motion-design productions, developed from visual concept through final animation. The project demonstrates sustained motion-design direction across an entire event piece rather than a single isolated animation.',video:'assets/videos/dict.mp4',poster:'assets/dict.jpg'},
  professional:{type:'PROFESSIONAL WORK · MULTIMEDIA · EVENT VISUALS',title:'Professional Multimedia & Event Productions',description:'A curated selection of professional work spanning live-event visuals, OBBs, motion graphics, brand animation and 3D/2D production.',role:'Motion graphics artist · Multimedia production · 3D/2D animation',tools:'After Effects · Blender · Photoshop · Premiere Pro',projectType:'Selected work created during professional employment',overview:'This collection represents production work created while working with Smarter Multimedia Services. The focus is on the breadth of professional output: branded event content, institutional visuals, openers, stage/LED material and animated production assets.',video:'assets/videos/professional-sample.mp4',poster:'assets/professional-work.jpg',gallery:['assets/gallery/prof-01.jpg','assets/gallery/prof-02.jpg','assets/gallery/prof-03.jpg','assets/gallery/prof-04.jpg']}
};
